# Generated by Django 4.1.7 on 2023-03-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Villager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('birthday', models.CharField(max_length=20)),
                ('liked_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_item', to='stardewApp.item')),
                ('loved_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loved_item', to='stardewApp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20)),
                ('hour', models.CharField(max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stardewApp.location')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stardewApp.season')),
                ('villager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stardewApp.villager')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stardewApp.location'),
        ),
        migrations.AddField(
            model_name='item',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stardewApp.season'),
        ),
    ]
